### ISSUE TITLE
关于如何用java实现一个shadowsocks客户端程序

### ISSUE THREAD

**Issue by ewangteng** [zhoulifu/ss-java#1]
你好，因为目前有项目涉及到该部分，所以想请教一下你。
我的项目是这样的，目前有一个web系统，想在系统中集成google搜索功能，所以需要自己实现一个sslocal程序，因为web项目是java实现的，所以如果用java实现一套与ssserver通信的util类，那么集成起来就非常方便了。
但是奈何我并不懂socks协议，也不太懂shadowsocks的实现，能否大体给我讲解一下？

**Comment by zhoulifu** [comment]
@ewangteng 你好。
与ssserver建立一个链接后，发送一个request告知需要转发的目标服务器的host与port，协议格式为：
```
        +------+----------+----------+
        | ATYP | BND.ADDR | BND.PORT |
        +------+----------+----------+
        |  1   | Variable |    2     |
        +------+----------+----------+
```
各字段含义等价于 [socks5 requests](https://tools.ietf.org/html/rfc1928) 中对应含义，此后可以开始正常发送数据。
所有交互数据均由[stream cipher](https://en.wikipedia.org/wiki/Stream_cipher)混淆后传输。因此建立连接后需先向服务器发送加密数据所使用的 [Initialization vector](https://en.wikipedia.org/wiki/Initialization_vector)，同样服务端返回的数据的开始一段为服务端加密使用的IV，IV后接着的就是加密后交互的数据了。IV长度固定，使用不同加密算法有不同长度的IV。
