### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [zhoulifu/ss-java#2]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/pers/zlf/sslocal/crypto/ShadowsocksKeyStore.java: Line number => 24: API name => SecretKeySpec:<BR> File name => src/main/java/pers/zlf/sslocal/utils/EncryptUtils.java: Line number => 36: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/pers/zlf/sslocal/crypto/impl/RC4MD5Crypto.java: Line number => 35: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/pers/zlf/sslocal/utils/EncryptUtils.java: Line number => 49: API name => MessageDigest:<BR> File name => src/main/java/pers/zlf/sslocal/crypto/impl/RC4MD5Crypto.java: Line number => 41: API name => MessageDigest:<BR> File name => src/main/java/pers/zlf/sslocal/crypto/ShadowsocksKeyStore.java: Line number => 24: API name => SecretKeySpec:<BR>

**Comment by zhoulifu** [comment]
Bot's noise
